export const REMOVE_ERROR_MESSAGE = "REMOVE_ERROR_MESSAGE";

export const USER_CREATE = "USER_CREATE";
export const USER_CREATE_SUCCESS = "USER_CREATE_SUCCESS";
export const USER_CREATE_FAIL = "USER_CREATE_FAIL";
